# Generated by Django 4.2.1 on 2023-06-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipos_seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro_id', models.CharField(max_length=10)),
                ('tipo_seguro_nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
